theme: jekyll-theme-architect
author: Claudia D'Agostino
title: PoliTo projects
description: Papers, presentations and thesis from my Bachelor's and Master's degrees in Biomedical engineering at PoliTo
